name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect node version
        id: detect-node-version
        run: echo "node_version=$(node -v | sed 's/[^0-9]*\([0-9]*\).*/\1/')" >> $GITHUB_OUTPUT
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.detect-node-version.outputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: . # Replace with your project's root if needed
          environment: |
            NODE_ENV=${{ env.NODE_ENV }}
            # Add other environment variables here as needed

      - name: Slack Notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'good'
          SLACK_TITLE: 'Deployment Successful'
          SLACK_MESSAGE: 'Deployment to Vercel was successful.'
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          SLACK_USERNAME: GitHub Actions

      - name: Slack Notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'danger'
          SLACK_TITLE: 'Deployment Failed'
          SLACK_MESSAGE: 'Deployment to Vercel failed. Check the logs for details.'
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          SLACK_USERNAME: GitHub Actions