name: Deploy Node.js to Vercel

on:
  push:
    branches:
      - main  # Or your main branch name
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build # Or your build command, e.g., "npm run build", "yarn build"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: .  # Adjust this if your project root is not the repository root
          scope: ${{ secrets.VERCEL_SCOPE }} # Optional: Add scope if needed.

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
          SLACK_TITLE: "Deployment Failed"
          SLACK_MESSAGE: "Deployment to Vercel failed. Check the logs for details."
          SLACK_USERNAME: GitHub Actions